[package]
name = "dylibsurfer-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
dylibsurfer-ir = { path = "../dylibsurfer-ir" }
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
